### ISSUE TITLE
[Feature] Recommendations page based on favourites?

### ISSUE THREAD

**Issue by younyokel** [re621/re621#6]
Hi. I know this can be hard to make but I'm simply giving an idea for a recommendations system based on user's favourites that doesn't exist in e621 but is pretty common in other imageboards. [I saw an YRE project](https://github.com/splineclaw/yre)  but it wasn't updated since 2019 and I don't know how to even check it out.

**Comment by bitWolfy** [comment]
That is a feature in the Legacy version "Recommended" link under "Related" on the search page.
I will definitely port to version 2.0 of the script.

Unfortunately, due to being run in the browser, it simply isn't great.
It basically just tallies up the most common tags in your favorites and suggests some search options based on that.

Whether or not I can implement something like the YRE project in a userscript – and whether it's practical to do so – remains to be seen.
